-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains all types with cyclic dependencies (between each other or to itself)
module OpenAI.TypeAlias where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified OpenAI.Common
import {-# SOURCE #-} OpenAI.Types.ChatCompletionMessageToolCall


-- | Defines an alias for the schema located at @components.schemas.FunctionParameters@ in the specification.
-- 
-- The parameters the functions accepts, described as a JSON Schema object. See the [guide](\/docs\/guides\/text-generation\/function-calling) for examples, and the [JSON Schema reference](https:\/\/json-schema.org\/understanding-json-schema\/) for documentation about the format. 
-- 
-- Omitting \`parameters\` defines a function with an empty parameter list.
type FunctionParameters = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.ChatCompletionMessageToolCalls@ in the specification.
-- 
-- The tool calls generated by the model, such as function calls.
type ChatCompletionMessageToolCalls = [ChatCompletionMessageToolCall]
