module OpenAI.Types.ChatCompletionMessageToolCall where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAI.Common
data ChatCompletionMessageToolCall
instance Show ChatCompletionMessageToolCall
instance Eq ChatCompletionMessageToolCall
instance FromJSON ChatCompletionMessageToolCall
instance ToJSON ChatCompletionMessageToolCall
data ChatCompletionMessageToolCallFunction'
instance Show ChatCompletionMessageToolCallFunction'
instance Eq ChatCompletionMessageToolCallFunction'
instance FromJSON ChatCompletionMessageToolCallFunction'
instance ToJSON ChatCompletionMessageToolCallFunction'
