module OpenAI.Types.ChatCompletionRequestMessageContentPartImage where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAI.Common
data ChatCompletionRequestMessageContentPartImage
instance Show ChatCompletionRequestMessageContentPartImage
instance Eq ChatCompletionRequestMessageContentPartImage
instance FromJSON ChatCompletionRequestMessageContentPartImage
instance ToJSON ChatCompletionRequestMessageContentPartImage
data ChatCompletionRequestMessageContentPartImageImageUrl'
instance Show ChatCompletionRequestMessageContentPartImageImageUrl'
instance Eq ChatCompletionRequestMessageContentPartImageImageUrl'
instance FromJSON ChatCompletionRequestMessageContentPartImageImageUrl'
instance ToJSON ChatCompletionRequestMessageContentPartImageImageUrl'
data ChatCompletionRequestMessageContentPartImageImageUrl'Detail'
instance Show ChatCompletionRequestMessageContentPartImageImageUrl'Detail'
instance Eq ChatCompletionRequestMessageContentPartImageImageUrl'Detail'
instance FromJSON ChatCompletionRequestMessageContentPartImageImageUrl'Detail'
instance ToJSON ChatCompletionRequestMessageContentPartImageImageUrl'Detail'
