module OpenAI.Types.ChatCompletionRequestToolMessage where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAI.Common
data ChatCompletionRequestToolMessage
instance Show ChatCompletionRequestToolMessage
instance Eq ChatCompletionRequestToolMessage
instance FromJSON ChatCompletionRequestToolMessage
instance ToJSON ChatCompletionRequestToolMessage
