module OpenAI.Types.ChatCompletionTokenLogprob where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAI.Common
data ChatCompletionTokenLogprob
instance Show ChatCompletionTokenLogprob
instance Eq ChatCompletionTokenLogprob
instance FromJSON ChatCompletionTokenLogprob
instance ToJSON ChatCompletionTokenLogprob
data ChatCompletionTokenLogprobTopLogprobs'
instance Show ChatCompletionTokenLogprobTopLogprobs'
instance Eq ChatCompletionTokenLogprobTopLogprobs'
instance FromJSON ChatCompletionTokenLogprobTopLogprobs'
instance ToJSON ChatCompletionTokenLogprobTopLogprobs'
