module OpenAI.Types.ChatCompletionToolChoiceOption where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAI.Common
data ChatCompletionToolChoiceOptionOneOf1
instance Show ChatCompletionToolChoiceOptionOneOf1
instance Eq ChatCompletionToolChoiceOptionOneOf1
instance FromJSON ChatCompletionToolChoiceOptionOneOf1
instance ToJSON ChatCompletionToolChoiceOptionOneOf1
data ChatCompletionToolChoiceOptionVariants
instance Show ChatCompletionToolChoiceOptionVariants
instance Eq ChatCompletionToolChoiceOptionVariants
instance FromJSON ChatCompletionToolChoiceOptionVariants
instance ToJSON ChatCompletionToolChoiceOptionVariants
type ChatCompletionToolChoiceOption = ChatCompletionToolChoiceOptionVariants
