-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema ChatCompletionNamedToolChoice
module OpenAI.Types.ChatCompletionNamedToolChoice where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified OpenAI.Common
import OpenAI.TypeAlias

-- | Defines the object schema located at @components.schemas.ChatCompletionNamedToolChoice@ in the specification.
-- 
-- Specifies a tool the model should use. Use to force the model to call a specific function.
data ChatCompletionNamedToolChoice = ChatCompletionNamedToolChoice {
  -- | function
  chatCompletionNamedToolChoiceFunction :: ChatCompletionNamedToolChoiceFunction'
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON ChatCompletionNamedToolChoice
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["function" Data.Aeson.Types.ToJSON..= chatCompletionNamedToolChoiceFunction obj] : ["type" Data.Aeson.Types.ToJSON..= Data.Aeson.Types.Internal.String "function"] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["function" Data.Aeson.Types.ToJSON..= chatCompletionNamedToolChoiceFunction obj] : ["type" Data.Aeson.Types.ToJSON..= Data.Aeson.Types.Internal.String "function"] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON ChatCompletionNamedToolChoice
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "ChatCompletionNamedToolChoice" (\obj -> GHC.Base.pure ChatCompletionNamedToolChoice GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "function"))}
-- | Create a new 'ChatCompletionNamedToolChoice' with all required fields.
mkChatCompletionNamedToolChoice :: ChatCompletionNamedToolChoiceFunction' -- ^ 'chatCompletionNamedToolChoiceFunction'
  -> ChatCompletionNamedToolChoice
mkChatCompletionNamedToolChoice chatCompletionNamedToolChoiceFunction = ChatCompletionNamedToolChoice{chatCompletionNamedToolChoiceFunction = chatCompletionNamedToolChoiceFunction}
-- | Defines the object schema located at @components.schemas.ChatCompletionNamedToolChoice.properties.function@ in the specification.
-- 
-- 
data ChatCompletionNamedToolChoiceFunction' = ChatCompletionNamedToolChoiceFunction' {
  -- | name: The name of the function to call.
  chatCompletionNamedToolChoiceFunction'Name :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON ChatCompletionNamedToolChoiceFunction'
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["name" Data.Aeson.Types.ToJSON..= chatCompletionNamedToolChoiceFunction'Name obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["name" Data.Aeson.Types.ToJSON..= chatCompletionNamedToolChoiceFunction'Name obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON ChatCompletionNamedToolChoiceFunction'
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "ChatCompletionNamedToolChoiceFunction'" (\obj -> GHC.Base.pure ChatCompletionNamedToolChoiceFunction' GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "name"))}
-- | Create a new 'ChatCompletionNamedToolChoiceFunction'' with all required fields.
mkChatCompletionNamedToolChoiceFunction' :: Data.Text.Internal.Text -- ^ 'chatCompletionNamedToolChoiceFunction'Name'
  -> ChatCompletionNamedToolChoiceFunction'
mkChatCompletionNamedToolChoiceFunction' chatCompletionNamedToolChoiceFunction'Name = ChatCompletionNamedToolChoiceFunction'{chatCompletionNamedToolChoiceFunction'Name = chatCompletionNamedToolChoiceFunction'Name}
