module OpenAI.Types.ChatCompletionRequestUserMessage where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAI.Common
data ChatCompletionRequestUserMessage
instance Show ChatCompletionRequestUserMessage
instance Eq ChatCompletionRequestUserMessage
instance FromJSON ChatCompletionRequestUserMessage
instance ToJSON ChatCompletionRequestUserMessage
data ChatCompletionRequestUserMessageContent'Variants
instance Show ChatCompletionRequestUserMessageContent'Variants
instance Eq ChatCompletionRequestUserMessageContent'Variants
instance FromJSON ChatCompletionRequestUserMessageContent'Variants
instance ToJSON ChatCompletionRequestUserMessageContent'Variants
