module OpenAI.Types.CreateChatCompletionRequest where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAI.Common
data CreateChatCompletionRequest
instance Show CreateChatCompletionRequest
instance Eq CreateChatCompletionRequest
instance FromJSON CreateChatCompletionRequest
instance ToJSON CreateChatCompletionRequest
data CreateChatCompletionRequestFunctionCall'OneOf1
instance Show CreateChatCompletionRequestFunctionCall'OneOf1
instance Eq CreateChatCompletionRequestFunctionCall'OneOf1
instance FromJSON CreateChatCompletionRequestFunctionCall'OneOf1
instance ToJSON CreateChatCompletionRequestFunctionCall'OneOf1
data CreateChatCompletionRequestFunctionCall'Variants
instance Show CreateChatCompletionRequestFunctionCall'Variants
instance Eq CreateChatCompletionRequestFunctionCall'Variants
instance FromJSON CreateChatCompletionRequestFunctionCall'Variants
instance ToJSON CreateChatCompletionRequestFunctionCall'Variants
data CreateChatCompletionRequestModel'OneOf2
instance Show CreateChatCompletionRequestModel'OneOf2
instance Eq CreateChatCompletionRequestModel'OneOf2
instance FromJSON CreateChatCompletionRequestModel'OneOf2
instance ToJSON CreateChatCompletionRequestModel'OneOf2
data CreateChatCompletionRequestModel'Variants
instance Show CreateChatCompletionRequestModel'Variants
instance Eq CreateChatCompletionRequestModel'Variants
instance FromJSON CreateChatCompletionRequestModel'Variants
instance ToJSON CreateChatCompletionRequestModel'Variants
data CreateChatCompletionRequestResponseFormat'
instance Show CreateChatCompletionRequestResponseFormat'
instance Eq CreateChatCompletionRequestResponseFormat'
instance FromJSON CreateChatCompletionRequestResponseFormat'
instance ToJSON CreateChatCompletionRequestResponseFormat'
data CreateChatCompletionRequestResponseFormat'Type'
instance Show CreateChatCompletionRequestResponseFormat'Type'
instance Eq CreateChatCompletionRequestResponseFormat'Type'
instance FromJSON CreateChatCompletionRequestResponseFormat'Type'
instance ToJSON CreateChatCompletionRequestResponseFormat'Type'
data CreateChatCompletionRequestStop'Variants
instance Show CreateChatCompletionRequestStop'Variants
instance Eq CreateChatCompletionRequestStop'Variants
instance FromJSON CreateChatCompletionRequestStop'Variants
instance ToJSON CreateChatCompletionRequestStop'Variants
