-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema CreateMessageRequest
module OpenAI.Types.CreateMessageRequest where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified OpenAI.Common
import OpenAI.TypeAlias

-- | Defines the object schema located at @components.schemas.CreateMessageRequest@ in the specification.
-- 
-- 
data CreateMessageRequest = CreateMessageRequest {
  -- | content: The content of the message.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 32768
  -- * Minimum length of 1
  createMessageRequestContent :: Data.Text.Internal.Text
  -- | file_ids: A list of [File](\/docs\/api-reference\/files) IDs that the message should use. There can be a maximum of 10 files attached to a message. Useful for tools like \`retrieval\` and \`code_interpreter\` that can access and use files.
  -- 
  -- Constraints:
  -- 
  -- * Must have a maximum of 10 items
  -- * Must have a minimum of 1 items
  , createMessageRequestFileIds :: (GHC.Maybe.Maybe ([Data.Text.Internal.Text]))
  -- | metadata: Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.
  , createMessageRequestMetadata :: (GHC.Maybe.Maybe (OpenAI.Common.Nullable Data.Aeson.Types.Internal.Object))
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON CreateMessageRequest
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["content" Data.Aeson.Types.ToJSON..= createMessageRequestContent obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("file_ids" Data.Aeson.Types.ToJSON..=)) (createMessageRequestFileIds obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("metadata" Data.Aeson.Types.ToJSON..=)) (createMessageRequestMetadata obj) : ["role" Data.Aeson.Types.ToJSON..= Data.Aeson.Types.Internal.String "user"] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["content" Data.Aeson.Types.ToJSON..= createMessageRequestContent obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("file_ids" Data.Aeson.Types.ToJSON..=)) (createMessageRequestFileIds obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("metadata" Data.Aeson.Types.ToJSON..=)) (createMessageRequestMetadata obj) : ["role" Data.Aeson.Types.ToJSON..= Data.Aeson.Types.Internal.String "user"] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON CreateMessageRequest
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "CreateMessageRequest" (\obj -> ((GHC.Base.pure CreateMessageRequest GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "content")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "file_ids")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "metadata"))}
-- | Create a new 'CreateMessageRequest' with all required fields.
mkCreateMessageRequest :: Data.Text.Internal.Text -- ^ 'createMessageRequestContent'
  -> CreateMessageRequest
mkCreateMessageRequest createMessageRequestContent = CreateMessageRequest{createMessageRequestContent = createMessageRequestContent,
                                                                          createMessageRequestFileIds = GHC.Maybe.Nothing,
                                                                          createMessageRequestMetadata = GHC.Maybe.Nothing}
