module OpenAI.Types.CreateEmbeddingResponse where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAI.Common
data CreateEmbeddingResponse
instance Show CreateEmbeddingResponse
instance Eq CreateEmbeddingResponse
instance FromJSON CreateEmbeddingResponse
instance ToJSON CreateEmbeddingResponse
data CreateEmbeddingResponseUsage'
instance Show CreateEmbeddingResponseUsage'
instance Eq CreateEmbeddingResponseUsage'
instance FromJSON CreateEmbeddingResponseUsage'
instance ToJSON CreateEmbeddingResponseUsage'
