-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema CreateModerationRequest
module OpenAI.Types.CreateModerationRequest where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified OpenAI.Common
import OpenAI.TypeAlias

-- | Defines the object schema located at @components.schemas.CreateModerationRequest@ in the specification.
-- 
-- 
data CreateModerationRequest = CreateModerationRequest {
  -- | input: The input text to classify
  createModerationRequestInput :: CreateModerationRequestInput'Variants
  -- | model: Two content moderations models are available: \`text-moderation-stable\` and \`text-moderation-latest\`.
  -- 
  -- The default is \`text-moderation-latest\` which will be automatically upgraded over time. This ensures you are always using our most accurate model. If you use \`text-moderation-stable\`, we will provide advanced notice before updating the model. Accuracy of \`text-moderation-stable\` may be slightly lower than for \`text-moderation-latest\`.
  , createModerationRequestModel :: (GHC.Maybe.Maybe CreateModerationRequestModel'Variants)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON CreateModerationRequest
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["input" Data.Aeson.Types.ToJSON..= createModerationRequestInput obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("model" Data.Aeson.Types.ToJSON..=)) (createModerationRequestModel obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["input" Data.Aeson.Types.ToJSON..= createModerationRequestInput obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("model" Data.Aeson.Types.ToJSON..=)) (createModerationRequestModel obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON CreateModerationRequest
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "CreateModerationRequest" (\obj -> (GHC.Base.pure CreateModerationRequest GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "input")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "model"))}
-- | Create a new 'CreateModerationRequest' with all required fields.
mkCreateModerationRequest :: CreateModerationRequestInput'Variants -- ^ 'createModerationRequestInput'
  -> CreateModerationRequest
mkCreateModerationRequest createModerationRequestInput = CreateModerationRequest{createModerationRequestInput = createModerationRequestInput,
                                                                                 createModerationRequestModel = GHC.Maybe.Nothing}
-- | Defines the oneOf schema located at @components.schemas.CreateModerationRequest.properties.input.oneOf@ in the specification.
-- 
-- The input text to classify
data CreateModerationRequestInput'Variants =
   CreateModerationRequestInput'Text Data.Text.Internal.Text
  | CreateModerationRequestInput'ListTText ([Data.Text.Internal.Text])
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON CreateModerationRequestInput'Variants
    where {toJSON (CreateModerationRequestInput'Text a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (CreateModerationRequestInput'ListTText a) = Data.Aeson.Types.ToJSON.toJSON a}
instance Data.Aeson.Types.FromJSON.FromJSON CreateModerationRequestInput'Variants
    where {parseJSON val = case (CreateModerationRequestInput'Text Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((CreateModerationRequestInput'ListTText Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched") of
                           {Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a;
                            Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a}}
-- | Defines the enum schema located at @components.schemas.CreateModerationRequest.properties.model.anyOf@ in the specification.
-- 
-- 
data CreateModerationRequestModel'OneOf2 =
   CreateModerationRequestModel'OneOf2Other Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | CreateModerationRequestModel'OneOf2Typed Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | CreateModerationRequestModel'OneOf2EnumTextModerationLatest -- ^ Represents the JSON value @"text-moderation-latest"@
  | CreateModerationRequestModel'OneOf2EnumTextModerationStable -- ^ Represents the JSON value @"text-moderation-stable"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON CreateModerationRequestModel'OneOf2
    where {toJSON (CreateModerationRequestModel'OneOf2Other val) = val;
           toJSON (CreateModerationRequestModel'OneOf2Typed val) = Data.Aeson.Types.ToJSON.toJSON val;
           toJSON (CreateModerationRequestModel'OneOf2EnumTextModerationLatest) = "text-moderation-latest";
           toJSON (CreateModerationRequestModel'OneOf2EnumTextModerationStable) = "text-moderation-stable"}
instance Data.Aeson.Types.FromJSON.FromJSON CreateModerationRequestModel'OneOf2
    where {parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "text-moderation-latest" -> CreateModerationRequestModel'OneOf2EnumTextModerationLatest
                                             | val GHC.Classes.== "text-moderation-stable" -> CreateModerationRequestModel'OneOf2EnumTextModerationStable
                                             | GHC.Base.otherwise -> CreateModerationRequestModel'OneOf2Other val)}
-- | Defines the oneOf schema located at @components.schemas.CreateModerationRequest.properties.model.anyOf@ in the specification.
-- 
-- Two content moderations models are available: \`text-moderation-stable\` and \`text-moderation-latest\`.
-- 
-- The default is \`text-moderation-latest\` which will be automatically upgraded over time. This ensures you are always using our most accurate model. If you use \`text-moderation-stable\`, we will provide advanced notice before updating the model. Accuracy of \`text-moderation-stable\` may be slightly lower than for \`text-moderation-latest\`.
data CreateModerationRequestModel'Variants =
   CreateModerationRequestModel'Text Data.Text.Internal.Text
  | CreateModerationRequestModel'CreateModerationRequestModel'OneOf2 CreateModerationRequestModel'OneOf2
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON CreateModerationRequestModel'Variants
    where {toJSON (CreateModerationRequestModel'Text a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (CreateModerationRequestModel'CreateModerationRequestModel'OneOf2 a) = Data.Aeson.Types.ToJSON.toJSON a}
instance Data.Aeson.Types.FromJSON.FromJSON CreateModerationRequestModel'Variants
    where {parseJSON val = case (CreateModerationRequestModel'Text Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((CreateModerationRequestModel'CreateModerationRequestModel'OneOf2 Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched") of
                           {Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a;
                            Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a}}
