module OpenAI.Types.CreateFineTuningJobRequest where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAI.Common
data CreateFineTuningJobRequest
instance Show CreateFineTuningJobRequest
instance Eq CreateFineTuningJobRequest
instance FromJSON CreateFineTuningJobRequest
instance ToJSON CreateFineTuningJobRequest
data CreateFineTuningJobRequestHyperparameters'
instance Show CreateFineTuningJobRequestHyperparameters'
instance Eq CreateFineTuningJobRequestHyperparameters'
instance FromJSON CreateFineTuningJobRequestHyperparameters'
instance ToJSON CreateFineTuningJobRequestHyperparameters'
data CreateFineTuningJobRequestHyperparameters'BatchSize'Variants
instance Show CreateFineTuningJobRequestHyperparameters'BatchSize'Variants
instance Eq CreateFineTuningJobRequestHyperparameters'BatchSize'Variants
instance FromJSON CreateFineTuningJobRequestHyperparameters'BatchSize'Variants
instance ToJSON CreateFineTuningJobRequestHyperparameters'BatchSize'Variants
data CreateFineTuningJobRequestHyperparameters'LearningRateMultiplier'Variants
instance Show CreateFineTuningJobRequestHyperparameters'LearningRateMultiplier'Variants
instance Eq CreateFineTuningJobRequestHyperparameters'LearningRateMultiplier'Variants
instance FromJSON CreateFineTuningJobRequestHyperparameters'LearningRateMultiplier'Variants
instance ToJSON CreateFineTuningJobRequestHyperparameters'LearningRateMultiplier'Variants
data CreateFineTuningJobRequestHyperparameters'NEpochs'Variants
instance Show CreateFineTuningJobRequestHyperparameters'NEpochs'Variants
instance Eq CreateFineTuningJobRequestHyperparameters'NEpochs'Variants
instance FromJSON CreateFineTuningJobRequestHyperparameters'NEpochs'Variants
instance ToJSON CreateFineTuningJobRequestHyperparameters'NEpochs'Variants
data CreateFineTuningJobRequestModel'OneOf2
instance Show CreateFineTuningJobRequestModel'OneOf2
instance Eq CreateFineTuningJobRequestModel'OneOf2
instance FromJSON CreateFineTuningJobRequestModel'OneOf2
instance ToJSON CreateFineTuningJobRequestModel'OneOf2
data CreateFineTuningJobRequestModel'Variants
instance Show CreateFineTuningJobRequestModel'Variants
instance Eq CreateFineTuningJobRequestModel'Variants
instance FromJSON CreateFineTuningJobRequestModel'Variants
instance ToJSON CreateFineTuningJobRequestModel'Variants
