module OpenAI.Types.CreateModerationRequest where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAI.Common
data CreateModerationRequest
instance Show CreateModerationRequest
instance Eq CreateModerationRequest
instance FromJSON CreateModerationRequest
instance ToJSON CreateModerationRequest
data CreateModerationRequestInput'Variants
instance Show CreateModerationRequestInput'Variants
instance Eq CreateModerationRequestInput'Variants
instance FromJSON CreateModerationRequestInput'Variants
instance ToJSON CreateModerationRequestInput'Variants
data CreateModerationRequestModel'OneOf2
instance Show CreateModerationRequestModel'OneOf2
instance Eq CreateModerationRequestModel'OneOf2
instance FromJSON CreateModerationRequestModel'OneOf2
instance ToJSON CreateModerationRequestModel'OneOf2
data CreateModerationRequestModel'Variants
instance Show CreateModerationRequestModel'Variants
instance Eq CreateModerationRequestModel'Variants
instance FromJSON CreateModerationRequestModel'Variants
instance ToJSON CreateModerationRequestModel'Variants
