module OpenAI.Types.CreateSpeechRequest where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAI.Common
data CreateSpeechRequest
instance Show CreateSpeechRequest
instance Eq CreateSpeechRequest
instance FromJSON CreateSpeechRequest
instance ToJSON CreateSpeechRequest
data CreateSpeechRequestModel'OneOf2
instance Show CreateSpeechRequestModel'OneOf2
instance Eq CreateSpeechRequestModel'OneOf2
instance FromJSON CreateSpeechRequestModel'OneOf2
instance ToJSON CreateSpeechRequestModel'OneOf2
data CreateSpeechRequestModel'Variants
instance Show CreateSpeechRequestModel'Variants
instance Eq CreateSpeechRequestModel'Variants
instance FromJSON CreateSpeechRequestModel'Variants
instance ToJSON CreateSpeechRequestModel'Variants
data CreateSpeechRequestResponseFormat'
instance Show CreateSpeechRequestResponseFormat'
instance Eq CreateSpeechRequestResponseFormat'
instance FromJSON CreateSpeechRequestResponseFormat'
instance ToJSON CreateSpeechRequestResponseFormat'
data CreateSpeechRequestVoice'
instance Show CreateSpeechRequestVoice'
instance Eq CreateSpeechRequestVoice'
instance FromJSON CreateSpeechRequestVoice'
instance ToJSON CreateSpeechRequestVoice'
