-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema DeleteFileResponse
module OpenAI.Types.DeleteFileResponse where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified OpenAI.Common
import OpenAI.TypeAlias

-- | Defines the object schema located at @components.schemas.DeleteFileResponse@ in the specification.
-- 
-- 
data DeleteFileResponse = DeleteFileResponse {
  -- | deleted
  deleteFileResponseDeleted :: GHC.Types.Bool
  -- | id
  , deleteFileResponseId :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON DeleteFileResponse
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["deleted" Data.Aeson.Types.ToJSON..= deleteFileResponseDeleted obj] : ["id" Data.Aeson.Types.ToJSON..= deleteFileResponseId obj] : ["object" Data.Aeson.Types.ToJSON..= Data.Aeson.Types.Internal.String "file"] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["deleted" Data.Aeson.Types.ToJSON..= deleteFileResponseDeleted obj] : ["id" Data.Aeson.Types.ToJSON..= deleteFileResponseId obj] : ["object" Data.Aeson.Types.ToJSON..= Data.Aeson.Types.Internal.String "file"] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON DeleteFileResponse
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "DeleteFileResponse" (\obj -> (GHC.Base.pure DeleteFileResponse GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "deleted")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "id"))}
-- | Create a new 'DeleteFileResponse' with all required fields.
mkDeleteFileResponse :: GHC.Types.Bool -- ^ 'deleteFileResponseDeleted'
  -> Data.Text.Internal.Text -- ^ 'deleteFileResponseId'
  -> DeleteFileResponse
mkDeleteFileResponse deleteFileResponseDeleted deleteFileResponseId = DeleteFileResponse{deleteFileResponseDeleted = deleteFileResponseDeleted,
                                                                                         deleteFileResponseId = deleteFileResponseId}
