module OpenAI.Types.DeleteAssistantFileResponse where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAI.Common
data DeleteAssistantFileResponse
instance Show DeleteAssistantFileResponse
instance Eq DeleteAssistantFileResponse
instance FromJSON DeleteAssistantFileResponse
instance ToJSON DeleteAssistantFileResponse
