-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema DeleteAssistantFileResponse
module OpenAI.Types.DeleteAssistantFileResponse where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified OpenAI.Common
import OpenAI.TypeAlias

-- | Defines the object schema located at @components.schemas.DeleteAssistantFileResponse@ in the specification.
-- 
-- Deletes the association between the assistant and the file, but does not delete the [File](\/docs\/api-reference\/files) object itself.
data DeleteAssistantFileResponse = DeleteAssistantFileResponse {
  -- | deleted
  deleteAssistantFileResponseDeleted :: GHC.Types.Bool
  -- | id
  , deleteAssistantFileResponseId :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON DeleteAssistantFileResponse
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["deleted" Data.Aeson.Types.ToJSON..= deleteAssistantFileResponseDeleted obj] : ["id" Data.Aeson.Types.ToJSON..= deleteAssistantFileResponseId obj] : ["object" Data.Aeson.Types.ToJSON..= Data.Aeson.Types.Internal.String "assistant.file.deleted"] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["deleted" Data.Aeson.Types.ToJSON..= deleteAssistantFileResponseDeleted obj] : ["id" Data.Aeson.Types.ToJSON..= deleteAssistantFileResponseId obj] : ["object" Data.Aeson.Types.ToJSON..= Data.Aeson.Types.Internal.String "assistant.file.deleted"] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON DeleteAssistantFileResponse
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "DeleteAssistantFileResponse" (\obj -> (GHC.Base.pure DeleteAssistantFileResponse GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "deleted")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "id"))}
-- | Create a new 'DeleteAssistantFileResponse' with all required fields.
mkDeleteAssistantFileResponse :: GHC.Types.Bool -- ^ 'deleteAssistantFileResponseDeleted'
  -> Data.Text.Internal.Text -- ^ 'deleteAssistantFileResponseId'
  -> DeleteAssistantFileResponse
mkDeleteAssistantFileResponse deleteAssistantFileResponseDeleted deleteAssistantFileResponseId = DeleteAssistantFileResponse{deleteAssistantFileResponseDeleted = deleteAssistantFileResponseDeleted,
                                                                                                                             deleteAssistantFileResponseId = deleteAssistantFileResponseId}
