-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema ListRunStepsResponse
module OpenAI.Types.ListRunStepsResponse where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified OpenAI.Common
import OpenAI.TypeAlias
import {-# SOURCE #-} OpenAI.Types.RunStepObject

-- | Defines the object schema located at @components.schemas.ListRunStepsResponse@ in the specification.
-- 
-- 
data ListRunStepsResponse = ListRunStepsResponse {
  -- | data
  listRunStepsResponseData :: ([RunStepObject])
  -- | first_id
  , listRunStepsResponseFirstId :: Data.Text.Internal.Text
  -- | has_more
  , listRunStepsResponseHasMore :: GHC.Types.Bool
  -- | last_id
  , listRunStepsResponseLastId :: Data.Text.Internal.Text
  -- | object
  , listRunStepsResponseObject :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON ListRunStepsResponse
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["data" Data.Aeson.Types.ToJSON..= listRunStepsResponseData obj] : ["first_id" Data.Aeson.Types.ToJSON..= listRunStepsResponseFirstId obj] : ["has_more" Data.Aeson.Types.ToJSON..= listRunStepsResponseHasMore obj] : ["last_id" Data.Aeson.Types.ToJSON..= listRunStepsResponseLastId obj] : ["object" Data.Aeson.Types.ToJSON..= listRunStepsResponseObject obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["data" Data.Aeson.Types.ToJSON..= listRunStepsResponseData obj] : ["first_id" Data.Aeson.Types.ToJSON..= listRunStepsResponseFirstId obj] : ["has_more" Data.Aeson.Types.ToJSON..= listRunStepsResponseHasMore obj] : ["last_id" Data.Aeson.Types.ToJSON..= listRunStepsResponseLastId obj] : ["object" Data.Aeson.Types.ToJSON..= listRunStepsResponseObject obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON ListRunStepsResponse
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "ListRunStepsResponse" (\obj -> ((((GHC.Base.pure ListRunStepsResponse GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "data")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "first_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "has_more")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "last_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "object"))}
-- | Create a new 'ListRunStepsResponse' with all required fields.
mkListRunStepsResponse :: [RunStepObject] -- ^ 'listRunStepsResponseData'
  -> Data.Text.Internal.Text -- ^ 'listRunStepsResponseFirstId'
  -> GHC.Types.Bool -- ^ 'listRunStepsResponseHasMore'
  -> Data.Text.Internal.Text -- ^ 'listRunStepsResponseLastId'
  -> Data.Text.Internal.Text -- ^ 'listRunStepsResponseObject'
  -> ListRunStepsResponse
mkListRunStepsResponse listRunStepsResponseData listRunStepsResponseFirstId listRunStepsResponseHasMore listRunStepsResponseLastId listRunStepsResponseObject = ListRunStepsResponse{listRunStepsResponseData = listRunStepsResponseData,
                                                                                                                                                                                     listRunStepsResponseFirstId = listRunStepsResponseFirstId,
                                                                                                                                                                                     listRunStepsResponseHasMore = listRunStepsResponseHasMore,
                                                                                                                                                                                     listRunStepsResponseLastId = listRunStepsResponseLastId,
                                                                                                                                                                                     listRunStepsResponseObject = listRunStepsResponseObject}
