module OpenAI.Types.ListPaginatedFineTuningJobsResponse where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAI.Common
data ListPaginatedFineTuningJobsResponse
instance Show ListPaginatedFineTuningJobsResponse
instance Eq ListPaginatedFineTuningJobsResponse
instance FromJSON ListPaginatedFineTuningJobsResponse
instance ToJSON ListPaginatedFineTuningJobsResponse
