module OpenAI.Types.ListAssistantFilesResponse where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAI.Common
data ListAssistantFilesResponse
instance Show ListAssistantFilesResponse
instance Eq ListAssistantFilesResponse
instance FromJSON ListAssistantFilesResponse
instance ToJSON ListAssistantFilesResponse
