module OpenAI.Types.MessageContentTextAnnotationsFilePathObject where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAI.Common
data MessageContentTextAnnotationsFilePathObject
instance Show MessageContentTextAnnotationsFilePathObject
instance Eq MessageContentTextAnnotationsFilePathObject
instance FromJSON MessageContentTextAnnotationsFilePathObject
instance ToJSON MessageContentTextAnnotationsFilePathObject
data MessageContentTextAnnotationsFilePathObjectFilePath'
instance Show MessageContentTextAnnotationsFilePathObjectFilePath'
instance Eq MessageContentTextAnnotationsFilePathObjectFilePath'
instance FromJSON MessageContentTextAnnotationsFilePathObjectFilePath'
instance ToJSON MessageContentTextAnnotationsFilePathObjectFilePath'
