-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema MessageFileObject
module OpenAI.Types.MessageFileObject where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified OpenAI.Common
import OpenAI.TypeAlias

-- | Defines the object schema located at @components.schemas.MessageFileObject@ in the specification.
-- 
-- A list of files attached to a \`message\`.
data MessageFileObject = MessageFileObject {
  -- | created_at: The Unix timestamp (in seconds) for when the message file was created.
  messageFileObjectCreatedAt :: GHC.Types.Int
  -- | id: The identifier, which can be referenced in API endpoints.
  , messageFileObjectId :: Data.Text.Internal.Text
  -- | message_id: The ID of the [message](\/docs\/api-reference\/messages) that the [File](\/docs\/api-reference\/files) is attached to.
  , messageFileObjectMessageId :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON MessageFileObject
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["created_at" Data.Aeson.Types.ToJSON..= messageFileObjectCreatedAt obj] : ["id" Data.Aeson.Types.ToJSON..= messageFileObjectId obj] : ["message_id" Data.Aeson.Types.ToJSON..= messageFileObjectMessageId obj] : ["object" Data.Aeson.Types.ToJSON..= Data.Aeson.Types.Internal.String "thread.message.file"] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["created_at" Data.Aeson.Types.ToJSON..= messageFileObjectCreatedAt obj] : ["id" Data.Aeson.Types.ToJSON..= messageFileObjectId obj] : ["message_id" Data.Aeson.Types.ToJSON..= messageFileObjectMessageId obj] : ["object" Data.Aeson.Types.ToJSON..= Data.Aeson.Types.Internal.String "thread.message.file"] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON MessageFileObject
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "MessageFileObject" (\obj -> ((GHC.Base.pure MessageFileObject GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "created_at")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "message_id"))}
-- | Create a new 'MessageFileObject' with all required fields.
mkMessageFileObject :: GHC.Types.Int -- ^ 'messageFileObjectCreatedAt'
  -> Data.Text.Internal.Text -- ^ 'messageFileObjectId'
  -> Data.Text.Internal.Text -- ^ 'messageFileObjectMessageId'
  -> MessageFileObject
mkMessageFileObject messageFileObjectCreatedAt messageFileObjectId messageFileObjectMessageId = MessageFileObject{messageFileObjectCreatedAt = messageFileObjectCreatedAt,
                                                                                                                  messageFileObjectId = messageFileObjectId,
                                                                                                                  messageFileObjectMessageId = messageFileObjectMessageId}
