module OpenAI.Types.MessageContentTextAnnotationsFileCitationObject where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAI.Common
data MessageContentTextAnnotationsFileCitationObject
instance Show MessageContentTextAnnotationsFileCitationObject
instance Eq MessageContentTextAnnotationsFileCitationObject
instance FromJSON MessageContentTextAnnotationsFileCitationObject
instance ToJSON MessageContentTextAnnotationsFileCitationObject
data MessageContentTextAnnotationsFileCitationObjectFileCitation'
instance Show MessageContentTextAnnotationsFileCitationObjectFileCitation'
instance Eq MessageContentTextAnnotationsFileCitationObjectFileCitation'
instance FromJSON MessageContentTextAnnotationsFileCitationObjectFileCitation'
instance ToJSON MessageContentTextAnnotationsFileCitationObjectFileCitation'
