-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema MessageContentTextAnnotationsFilePathObject
module OpenAI.Types.MessageContentTextAnnotationsFilePathObject where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified OpenAI.Common
import OpenAI.TypeAlias

-- | Defines the object schema located at @components.schemas.MessageContentTextAnnotationsFilePathObject@ in the specification.
-- 
-- A URL for the file that\'s generated when the assistant used the \`code_interpreter\` tool to generate a file.
data MessageContentTextAnnotationsFilePathObject = MessageContentTextAnnotationsFilePathObject {
  -- | end_index
  -- 
  -- Constraints:
  -- 
  -- * Minimum  of 0.0
  messageContentTextAnnotationsFilePathObjectEndIndex :: GHC.Types.Int
  -- | file_path
  , messageContentTextAnnotationsFilePathObjectFilePath :: MessageContentTextAnnotationsFilePathObjectFilePath'
  -- | start_index
  -- 
  -- Constraints:
  -- 
  -- * Minimum  of 0.0
  , messageContentTextAnnotationsFilePathObjectStartIndex :: GHC.Types.Int
  -- | text: The text in the message content that needs to be replaced.
  , messageContentTextAnnotationsFilePathObjectText :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON MessageContentTextAnnotationsFilePathObject
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["end_index" Data.Aeson.Types.ToJSON..= messageContentTextAnnotationsFilePathObjectEndIndex obj] : ["file_path" Data.Aeson.Types.ToJSON..= messageContentTextAnnotationsFilePathObjectFilePath obj] : ["start_index" Data.Aeson.Types.ToJSON..= messageContentTextAnnotationsFilePathObjectStartIndex obj] : ["text" Data.Aeson.Types.ToJSON..= messageContentTextAnnotationsFilePathObjectText obj] : ["type" Data.Aeson.Types.ToJSON..= Data.Aeson.Types.Internal.String "file_path"] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["end_index" Data.Aeson.Types.ToJSON..= messageContentTextAnnotationsFilePathObjectEndIndex obj] : ["file_path" Data.Aeson.Types.ToJSON..= messageContentTextAnnotationsFilePathObjectFilePath obj] : ["start_index" Data.Aeson.Types.ToJSON..= messageContentTextAnnotationsFilePathObjectStartIndex obj] : ["text" Data.Aeson.Types.ToJSON..= messageContentTextAnnotationsFilePathObjectText obj] : ["type" Data.Aeson.Types.ToJSON..= Data.Aeson.Types.Internal.String "file_path"] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON MessageContentTextAnnotationsFilePathObject
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "MessageContentTextAnnotationsFilePathObject" (\obj -> (((GHC.Base.pure MessageContentTextAnnotationsFilePathObject GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "end_index")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "file_path")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "start_index")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "text"))}
-- | Create a new 'MessageContentTextAnnotationsFilePathObject' with all required fields.
mkMessageContentTextAnnotationsFilePathObject :: GHC.Types.Int -- ^ 'messageContentTextAnnotationsFilePathObjectEndIndex'
  -> MessageContentTextAnnotationsFilePathObjectFilePath' -- ^ 'messageContentTextAnnotationsFilePathObjectFilePath'
  -> GHC.Types.Int -- ^ 'messageContentTextAnnotationsFilePathObjectStartIndex'
  -> Data.Text.Internal.Text -- ^ 'messageContentTextAnnotationsFilePathObjectText'
  -> MessageContentTextAnnotationsFilePathObject
mkMessageContentTextAnnotationsFilePathObject messageContentTextAnnotationsFilePathObjectEndIndex messageContentTextAnnotationsFilePathObjectFilePath messageContentTextAnnotationsFilePathObjectStartIndex messageContentTextAnnotationsFilePathObjectText = MessageContentTextAnnotationsFilePathObject{messageContentTextAnnotationsFilePathObjectEndIndex = messageContentTextAnnotationsFilePathObjectEndIndex,
                                                                                                                                                                                                                                                                                                          messageContentTextAnnotationsFilePathObjectFilePath = messageContentTextAnnotationsFilePathObjectFilePath,
                                                                                                                                                                                                                                                                                                          messageContentTextAnnotationsFilePathObjectStartIndex = messageContentTextAnnotationsFilePathObjectStartIndex,
                                                                                                                                                                                                                                                                                                          messageContentTextAnnotationsFilePathObjectText = messageContentTextAnnotationsFilePathObjectText}
-- | Defines the object schema located at @components.schemas.MessageContentTextAnnotationsFilePathObject.properties.file_path@ in the specification.
-- 
-- 
data MessageContentTextAnnotationsFilePathObjectFilePath' = MessageContentTextAnnotationsFilePathObjectFilePath' {
  -- | file_id: The ID of the file that was generated.
  messageContentTextAnnotationsFilePathObjectFilePath'FileId :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON MessageContentTextAnnotationsFilePathObjectFilePath'
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["file_id" Data.Aeson.Types.ToJSON..= messageContentTextAnnotationsFilePathObjectFilePath'FileId obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["file_id" Data.Aeson.Types.ToJSON..= messageContentTextAnnotationsFilePathObjectFilePath'FileId obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON MessageContentTextAnnotationsFilePathObjectFilePath'
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "MessageContentTextAnnotationsFilePathObjectFilePath'" (\obj -> GHC.Base.pure MessageContentTextAnnotationsFilePathObjectFilePath' GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "file_id"))}
-- | Create a new 'MessageContentTextAnnotationsFilePathObjectFilePath'' with all required fields.
mkMessageContentTextAnnotationsFilePathObjectFilePath' :: Data.Text.Internal.Text -- ^ 'messageContentTextAnnotationsFilePathObjectFilePath'FileId'
  -> MessageContentTextAnnotationsFilePathObjectFilePath'
mkMessageContentTextAnnotationsFilePathObjectFilePath' messageContentTextAnnotationsFilePathObjectFilePath'FileId = MessageContentTextAnnotationsFilePathObjectFilePath'{messageContentTextAnnotationsFilePathObjectFilePath'FileId = messageContentTextAnnotationsFilePathObjectFilePath'FileId}
