module OpenAI.Types.RunObject where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAI.Common
data RunObject
instance Show RunObject
instance Eq RunObject
instance FromJSON RunObject
instance ToJSON RunObject
data RunObjectLastError'NonNullable
instance Show RunObjectLastError'NonNullable
instance Eq RunObjectLastError'NonNullable
instance FromJSON RunObjectLastError'NonNullable
instance ToJSON RunObjectLastError'NonNullable
data RunObjectLastError'NonNullableCode'
instance Show RunObjectLastError'NonNullableCode'
instance Eq RunObjectLastError'NonNullableCode'
instance FromJSON RunObjectLastError'NonNullableCode'
instance ToJSON RunObjectLastError'NonNullableCode'
data RunObjectRequiredAction'NonNullable
instance Show RunObjectRequiredAction'NonNullable
instance Eq RunObjectRequiredAction'NonNullable
instance FromJSON RunObjectRequiredAction'NonNullable
instance ToJSON RunObjectRequiredAction'NonNullable
data RunObjectRequiredAction'NonNullableSubmitToolOutputs'
instance Show RunObjectRequiredAction'NonNullableSubmitToolOutputs'
instance Eq RunObjectRequiredAction'NonNullableSubmitToolOutputs'
instance FromJSON RunObjectRequiredAction'NonNullableSubmitToolOutputs'
instance ToJSON RunObjectRequiredAction'NonNullableSubmitToolOutputs'
data RunObjectStatus'
instance Show RunObjectStatus'
instance Eq RunObjectStatus'
instance FromJSON RunObjectStatus'
instance ToJSON RunObjectStatus'
data RunObjectTools'Variants
instance Show RunObjectTools'Variants
instance Eq RunObjectTools'Variants
instance FromJSON RunObjectTools'Variants
instance ToJSON RunObjectTools'Variants
