module OpenAI.Types.RunStepObject where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAI.Common
data RunStepObject
instance Show RunStepObject
instance Eq RunStepObject
instance FromJSON RunStepObject
instance ToJSON RunStepObject
data RunStepObjectLastError'NonNullable
instance Show RunStepObjectLastError'NonNullable
instance Eq RunStepObjectLastError'NonNullable
instance FromJSON RunStepObjectLastError'NonNullable
instance ToJSON RunStepObjectLastError'NonNullable
data RunStepObjectLastError'NonNullableCode'
instance Show RunStepObjectLastError'NonNullableCode'
instance Eq RunStepObjectLastError'NonNullableCode'
instance FromJSON RunStepObjectLastError'NonNullableCode'
instance ToJSON RunStepObjectLastError'NonNullableCode'
data RunStepObjectStatus'
instance Show RunStepObjectStatus'
instance Eq RunStepObjectStatus'
instance FromJSON RunStepObjectStatus'
instance ToJSON RunStepObjectStatus'
data RunStepObjectStepDetails'Variants
instance Show RunStepObjectStepDetails'Variants
instance Eq RunStepObjectStepDetails'Variants
instance FromJSON RunStepObjectStepDetails'Variants
instance ToJSON RunStepObjectStepDetails'Variants
data RunStepObjectType'
instance Show RunStepObjectType'
instance Eq RunStepObjectType'
instance FromJSON RunStepObjectType'
instance ToJSON RunStepObjectType'
