module OpenAI.Types.RunStepDetailsToolCallsCodeObject where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAI.Common
data RunStepDetailsToolCallsCodeObject
instance Show RunStepDetailsToolCallsCodeObject
instance Eq RunStepDetailsToolCallsCodeObject
instance FromJSON RunStepDetailsToolCallsCodeObject
instance ToJSON RunStepDetailsToolCallsCodeObject
data RunStepDetailsToolCallsCodeObjectCodeInterpreter'
instance Show RunStepDetailsToolCallsCodeObjectCodeInterpreter'
instance Eq RunStepDetailsToolCallsCodeObjectCodeInterpreter'
instance FromJSON RunStepDetailsToolCallsCodeObjectCodeInterpreter'
instance ToJSON RunStepDetailsToolCallsCodeObjectCodeInterpreter'
data RunStepDetailsToolCallsCodeObjectCodeInterpreter'Outputs'Variants
instance Show RunStepDetailsToolCallsCodeObjectCodeInterpreter'Outputs'Variants
instance Eq RunStepDetailsToolCallsCodeObjectCodeInterpreter'Outputs'Variants
instance FromJSON RunStepDetailsToolCallsCodeObjectCodeInterpreter'Outputs'Variants
instance ToJSON RunStepDetailsToolCallsCodeObjectCodeInterpreter'Outputs'Variants
