module OpenAI.Types.RunStepDetailsToolCallsCodeOutputImageObject where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified OpenAI.Common
data RunStepDetailsToolCallsCodeOutputImageObject
instance Show RunStepDetailsToolCallsCodeOutputImageObject
instance Eq RunStepDetailsToolCallsCodeOutputImageObject
instance FromJSON RunStepDetailsToolCallsCodeOutputImageObject
instance ToJSON RunStepDetailsToolCallsCodeOutputImageObject
data RunStepDetailsToolCallsCodeOutputImageObjectImage'
instance Show RunStepDetailsToolCallsCodeOutputImageObjectImage'
instance Eq RunStepDetailsToolCallsCodeOutputImageObjectImage'
instance FromJSON RunStepDetailsToolCallsCodeOutputImageObjectImage'
instance ToJSON RunStepDetailsToolCallsCodeOutputImageObjectImage'
